@extends('layouts.app')


@section('content')
<div class="section">
	<div class="container">
		<div class="row">
			<h1 style="font-size:3.5rem" class="mt-5 sdl-h1 font-weight-normal text-black">
				<span>
				Política de Privacidade
				</span>
			</h1>
		</div>
		<div class="row mt-4">
			<div class="col-12 text-right">
				<span class="font-weight-light">Data da última atualização: 14 de Agosto de 2020 </span>
			</div>
		</div>
		<div class="row mt-4">	
			<div class="col-12 text-justify">
				<p>Esta “<span class="font-weight-bold">Política de Privacidade</span>”, doravante assim denominada, estabelece as regras referentes à obtenção eutilização de informações que serão inseridas por você, na qualidade de “Usuário”, ao acessar o aplicativo (“<span class="font-weight-bold">APP</span>”) da SmartDriving Labs Serviços Veiculares Inteligentes Ltda., inscrita no CNPJ 32.740.186/0001-01 (“<span class="font-weight-bold">Smart Driving Labs</span>”), informando assim quais informações são coletadas, a forma como essas informações são tratadas e o eventual compartilhamento e/ou exclusão desses dados.</p>
				<p>Importante que você na qualidade de Usuário do APP leia com atenção e esteja ciente das seguintes regras: ao acessar, usar e/ou se cadastrar no APP e ao contratar os serviços da Smart Driving Labs, seja de que for a for, você estará automaticamente e integralmente concordando com a Política de Privacidade aqui disposta, bem como com as demais políticas e/ou regras dos Termos de Uso constante do link https://smartdriving.com.br/politica/. Assim, caso você não concorde com todas estas condições, não use o APP e/ou os demais serviços da Smart Driving Labs.</p>
				<p>Desse modo, com a aceitação da presente Política de Privacidade por você na qualidade de Usuário, significa que você concorda epermite o acesso as suas informações e dados a partir da realização do primeiro acesso que fizer do APP. Se o Usuário não concordar com a política de tratamento de dados descrita neste documento deve se abster de utilizar o APP.</p>
				<p>O Usuário declara-se ciente, desde já, que é de sua exclusiva responsabilidade: (i) inserir apenas informações verdadeiras no APP; (ii) zelar pelos dados de sua identificação digital individual sempre que acessar o APP, informando-os apenas em operações em que exista a proteção de dados; (iii) manter em segredo sua senha de acesso, além de utilizar as tecnologias fornecidas pelo APP para proteger sua privacidade perante terceiros; (iv) cumprir rigorosamente todas as determinações e procedimentos previstos nesta Política de Privacidade.</p>
				<p>Caso reste alguma dúvida, após a leitura desta Política de Privacidade, entre em contato conosco, pelo e-mail contato@smartdriving.com.br .</p>
				<h6>Objeto e Finalidade do Recolhimento de Dados</h6>
				<p>Inicialmente, fica aqui certo e ajustado que as informações coletadas poderão ser retidas, bem como armazenadas, processadas, acessadas, usadas e compartilhadas obedecidos, sempre e quando aplicáveis, a Constituição Federal, o Código de Defesa do Consumidor, o Código Civil, o Marco Civil da Internet (Lei Federal n. 12.965/2014), seu decreto regulamentador (Decreto 8.771/2016), a Lei Geral de Proteção de Dados (Lei Federal n. 13.709/2018) e demais normas setoriais ou gerais sobre o tema.</p>
				<p>A Smart Driving Labs coleta todas as informações inseridas pelo Usuário quando da utilização do APP. Nesse sentido, quando você acessa o APP para cadastro, suas informações serão solicitadas e coletadas. Exemplificativamente, mas não se limitando, as seguintes informações serão coletadas no momento do cadastro de um novo Usuário: (i) nome completo; (ii) número de telefone; (iii) endereço completo; (iv) endereço de e-mail; (v) senha de acesso; (vi) informações referentes ao pagamento.</p>
				<p>Além disso, também são armazenadas, automaticamente, algumas informações a partir do momento em que o APP é iniciado e conectado com a plataforma de serviços da Smart Driving Labs, tais como: (i) dados de localização; (ii) dados de geolocalização; (iii) dados de dirigibilidade, incluindo distâncias percorridas, aceleração, ganho e perda de velocidade, direção e rotas praticadas; (iv) dados da agenda de contato, caso o Usuário solicite essa opção de sincronização; (v) dados de uso da bateria; (vi) dados de uso do telefone; (vii) informações sobre o número IP, data e hora de inicialização do Aplicativo; e (viii) dados obtidos pelos demais sensores presentes no dispositivo eletrônico instalado no veículo do usuário, tais quais o acelerômetro e o sensor de presença.</p>
				<p>A utilização do APP, em alguns casos, também poderá ensejar a coleta de outras informações sobre dispositivos utilizados pelo Usuário, a exemplo do modelo de hardware, versão do sistema operacional, informações de rede móvel, identificadores exclusivos de produtos, características do dispositivo, do navegador, Protocolo de Internet (IP, com data e hora), origem do IP, informações sobre cliques, dentre outros. </p>
				<p>A Smart Driving Labs também poderá utilizar outras tecnologias, como cookies, pixel tags, beacons e local shared objects, para coletar informações do Usuário e melhorar sua experiência de navegação.</p>
				<p>Desta forma, por meio do aceite destes Termos de Uso, o Usuário se declara ciente das informações coletadas por meio do APP e manifesta consentimento livre, consciente, expresso e declarado com relação à coleta de tais informações.</p>
				<p>Os dados pessoais dos Usuários serão concedidos à Smart Driving Labs quando da realização do cadastro necessário à utilização do APP preferencialmente com vistas a (i) manter uma adequada relação com o Usuário; (ii) facilitar o acesso aos serviços prestados pela Smart Driving Labs; (iii) prestar, gerenciar, administrar, ampliar e melhorar os serviços a serem prestados por meio do APP; (iv) atender adequadamente qualquer consulta ou solicitação de informação realizada pelo Usuário; (v) eventualmente enviar informativos sobre produtos e/ou serviços de interesse aos Usuários; (vi) divulgar alterações, inovações ou promoções sobre os produtos e serviços da empresa Smart Driving Labs e de seus parceiros.</p>
				<p>Ao utilizar o APP você autoriza a Smart Driving Labs a enviar correios eletrônicos e/ou mensagem SMS ou mensagens via what’s up e notificações por push e/ou em aplicativos, com conteúdo de natureza informativa e promocional, notadamente se forem relacionados, direta ou indiretamente, aos serviços a serem prestados pela Smart Driving Labs.</p>
				<p>Salvo expressa disposição contrária, a submissão de seus dados à Smart Driving Labs na qualidade de Usuário é totalmente voluntária e você entende e declara reconhecer que a falta de qualquer dos dados solicitados poderá afetar a qualidade dos serviços a serem prestados pela Smart Driving Labs. </p>
				<p>É facultado ao Usuário bloquear a coleta de alguns tipos de informações, tais como cookies. Caso essa configuração seja implementada, no entanto, é possível que algumas das funções oferecidas pelo APP não funcionem corretamente.</p>
				<p>Assim, o Usuário desde já se encontra ciente acerca das informações coletadas pelo APP e expressa o mais absoluto e livre consentimento, expresso e informado, com relação à coleta de tais informações e dados, nos termos desta Política de Privacidade.</p>
				<p>Ademais, o Usuário ao utilizar o APP automaticamente concede o seu livre e expresso consentimento para que a Smart Driving Labs utilize as informações coletadas por meio do APP para fins publicitários, dentro do próprio APP e por meio das informações de contato fornecidas pelo Usuário ao acessar o APP, nos termos descritos nesta Política de Privacidade.</p>
				<p>Entretanto, caso não deseje mais receber informativos publicitários da Smart Driving Labs, envie um e-mail para contato@smartdriving.com.br .</p>
				<p>É, ainda, importante atentar que o APP pode conter links para outras páginas, como redes sociais ou lojas virtuais, entre outras, que possuem Política de Privacidade com previsões diversas das deste documento. Dessa forma, a Smart Driving Labs não se responsabiliza pela coleta, utilização, compartilhamento e armazenamento de dados dos Usuários pelos responsáveis por tais páginas.</p>
				<h6>Forma de Compartilhamento</h6>
				<p>A Smart Driving Labs poderá compartilhar os dados em referência com as demais empresas parceiras da Smart Driving Labs e com terceiros de forma anonimizada, com o que o Usuário desde logo concorda expressamente, o que poderá ocorrer especialmente nas seguintes hipóteses: (i) caso a viabilização dos negócios e/ou serviços oferecidos pela Smart Driving Labs dependa do repasse de dados a parceiros;  (ii) para a melhor proteção dos interesses da Smart Driving Labs em qualquer tipo de conflito, incluindo ações judiciais, como, mas não se limitando a, quando exista a necessidade de identificar ou revelar dados de Usuário que esteja utilizando o APP com propósitos ilícitos; (iii) mediante ordem judicial ou pelo requerimento de autoridades administrativas que detenham competência legal para sua requisição.</p>
				<h6>Segurança e Confidencialidade</h6>
				<p>As informações coletadas são tratadas pela Smart Driving Labs como sigilosas, e qualquer funcionário ou prestador de serviços da Smart Driving Labs que entre em contato com tais informações se comprometerá a não desvirtuar sua utilização, bem como em não asusar de modo destoante do previsto nesta Política de Privacidade. A Smart Driving Labs sempre empregará todos os esforços razoáveis de mercado para garantir a segurança de seus sistemas na guarda de referidos dados.</p>
				<p>Assim sendo, a segurança das informações compartilhadas e disponibilizadas por você ao utilizar o APP é muito importante para a Smart Driving Labs, que obedece aos padrões de segurança do setor para ajudar a proteger as informações coletadas. Entretanto, não existe nenhum método de armazenamento eletrônico que seja totalmente seguro. Dessa forma, embora a Smart Driving Labs envide seus melhores esforços para proteger as informações pessoais coletadas, esta não concede garantias absolutas de segurança.</p>
				<p>Dessa forma, esta Política de Privacidade representa esforço da Smart Driving Labs buscando resguardar as informações dos Usuários de seu APP. No entanto, em razão da própria natureza da Internet, não é possível garantir que terceiros mal intencionados não logrem sucesso em acessar indevidamente as informações armazenadas pela Smart Driving Labs.</p>
				<h6>Exclusão de informações</h6>
				<p>As informações referidas na presente Política de Privacidade serão automaticamente excluídas quando deixarem de ser úteis aos propósitos para os quais foram coletadas. </p>
				<p>No entanto, caso o Usuário deseje antecipar essa exclusão, poderá requerê-la à Smart Driving Labs, pelo e-mail: contato@smartdriving.com.br . Em tal circunstância, a Smart Driving Labs envidará os seus melhores esforços para atender a todos os pedidos no menor espaço de tempo possível. Porém, o Usuário deve estar ciente de que, mesmo em caso de requisição de exclusão, a Smart Driving Labs respeitará o prazo de armazenamento mínimo de informações determinado pela legislação brasileira.</p>
				<h6>Atualização desta Política de Privacidade</h6>
				<p>Assim, a Smart Driving Labs reserva-se ao direito de alterar esta Política de Privacidade, bem como qualquer outra política do APP a qualquer momento e ao seu exclusivo critério. As alterações entrarão em vigor no momento da respectiva publicação no APP. O uso do APP após a publicação da nova Política de Privacidade constituirá aceitação automática dessas eventuais alterações da Política de Privacidade. </p>
				<p>Dessa forma, aconselhamos você a reler a Política de Privacidade sempre que acessar o APP. Se você não concordar com os termos alterados da Política de Privacidade, deverá descontinuar o uso do site. Para facilitar a visualização, já no início desta Política informamos a data da última atualização.</p>
				<p>No caso de alterações significativas desta Política de Privacidade ou da forma como a Smart Driving Labs usa suas informações, a Smart Driving Labs promoverá esforços razoáveis para dar publicidade a estas alterações, da forma que entender conveniente e adequada. Ressalta-se que a Smart Driving Labs não promoverá alterações na Política de Privacidade com o objetivo de prejudicar ou reduzir direitos do Usuário.</p>
				<h6>Legislação e Foro Competentes</h6>
				<p>Esta Política de Privacidade será regida, interpretada e executada de acordo com as leis da República Federativa do Brasil, independentemente dos conflitos dessas leis com leis de outros estados ou países, sendo competente o foro da Comarca de São Paulo, Estado de São Paulo, Brasil, que prevalecerá sobre qualquer outro, por mais privilegiado que seja, e será julgado conforme as leis da República Federativa do Brasil. </p>
				<p>O Usuário consente, expressamente, com a competência desse juízo, e renúncia, neste ato, à competência de qualquer outro foro, por mais privilegiado que seja ou venha a ser.</p>
			</div>
		</div>
	</div>
</div>
@endsection

@section('scripts')

@endsection
